//////// SPACES

export const FETCH_SPACES = 'FETCH_SPACES';
export const FETCH_SPACES_PENDING = 'FETCH_SPACES_PENDING';
export const FETCH_SPACES_FULFILLED = 'FETCH_SPACES_FULFILLED';



export const ADD_SPACE = 'ADD_SPACE';
export const ADD_SPACE_PENDING = 'ADD_SPACE_PENDING';
export const ADD_SPACE_FULFILLED = 'ADD_SPACE_FULFILLED';



export const DELETE_SPACE = 'DELETE_SPACE';
export const DELETE_SPACE_PENDING = 'DELETE_SPACE_PENDING';
export const DELETE_SPACE_FULFILLED = 'DELETE_SPACE_FULFILLED';


export const UPDATE_SPACE = 'UPDATE_SPACE';
export const UPDATE_SPACE_PENDING = 'UPDATE_SPACE_PENDING';
export const UPDATE_SPACE_FULFILLED = 'UPDATE_SPACE_FULFILLED';


/////// EVENTS

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING';
export const FETCH_EVENTS_FULFILLED = 'FETCH_EVENTS_FULFILLED';
