//////// SPACES

export const FETCH_SPACES = 'FETCH_SPACES';
export const FETCH_SPACES_PENDING = 'FETCH_SPACES_PENDING';
export const FETCH_SPACES_FULFILLED = 'FETCH_SPACES_FULFILLED';


export const ADD_SPACE = 'ADD_SPACE';
export const ADD_SPACE_PENDING = 'ADD_SPACE_PENDING';
export const ADD_SPACE_FULFILLED = 'ADD_SPACE_FULFILLED';


export const DELETE_SPACE = 'DELETE_SPACE';
export const DELETE_SPACE_PENDING = 'DELETE_SPACE_PENDING';
export const DELETE_SPACE_FULFILLED = 'DELETE_SPACE_FULFILLED';


export const UPDATE_SPACE = 'UPDATE_SPACE';
export const UPDATE_SPACE_PENDING = 'UPDATE_SPACE_PENDING';
export const UPDATE_SPACE_FULFILLED = 'UPDATE_SPACE_FULFILLED';



/////// EVENTS


export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING';
export const FETCH_EVENTS_FULFILLED = 'FETCH_EVENTS_FULFILLED';

export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENT_PENDING = 'ADD_EVENT_PENDING';
export const ADD_EVENT_FULFILLED = 'ADD_EVENT_FULFILLED';


export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_PENDING = 'DELETE_EVENT_PENDING';
export const DELETE_EVENT_FULFILLED = 'DELETE_EVENT_FULFILLED';


export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_PENDING = 'UPDATE_EVENT_PENDING';
export const UPDATE_EVENT_FULFILLED = 'UPDATE_EVENT_FULFILLED';



/////// TEXT


export const FETCH_TEXT = 'FETCH_TEXT';
export const FETCH_TEXT_PENDING = 'FETCH_TEXT_PENDING';
export const FETCH_TEXT_FULFILLED = 'FETCH_TEXT_FULFILLED';


export const UPDATE_TEXT = 'UPDATE_TEXT';
export const UPDATE_TEXT_PENDING = 'UPDATE_TEXT_PENDING';
export const UPDATE_TEXT_FULFILLED = 'UPDATE_TEXT_FULFILLED';
