//////// SPACES

export const FETCH_SPACES = 'FETCH_SPACES';
export const FETCH_SPACES_PENDING = 'FETCH_SPACES_PENDING';
export const FETCH_SPACES_FULFILLED = 'FETCH_SPACES_FULFILLED';




/////// EVENTS

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING';
export const FETCH_EVENTS_FULFILLED = 'FETCH_EVENTS_FULFILLED';
